version: "3.3"

services:
  sdnr:
    image: openbackhaul/mwdomaincontroller:v5.0.6-SR15
    container_name: sdnr
    ports:
      - "8181:8181"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=120
    # uncomment volumes section to stores logs in host folder /var/tmp/mwdomaincontroller/logs
    #volumes:
      #- /var/tmp/mwdomaincontroller/logs:/opt/opendaylight/data/log
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"
